version: '3.8'

services:
  copilot-api:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.copilot
    expose:
      - "5001"
    networks:
      - copilot-network
    restart: unless-stopped

  verifier:
    env_file:
      - .env
    build:
      context: .
      dockerfile: verifier.Dockerfile
    expose:
      - "5002"
    environment:
      - API_KEY=${API_KEY}
    networks:
      - copilot-network
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "5000:5000"
    volumes:
      - ${HOST_CERTS_DIR}:/etc/nginx/certs:ro
    depends_on:
      - copilot-api
    networks:
      - copilot-network
    restart: unless-stopped

networks:
  copilot-network:
    driver: bridge
